[xdebug]
xdebug.mode=${XDEBUG_MODE}
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
; Uncomment while diagnosing:
; xdebug.log=/tmp/xdebug.log
; xdebug.log_level=7
